import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile,mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve,extname} from 'node:path';
import {createServer} from 'node:http';
import {execFileSync} from 'node:child_process';
import {chromium} from 'playwright';

const root=resolve(import.meta.dirname,'..'), folder=await mkdtemp(join(tmpdir(),'frame-studio-'));
const shots=process.env.QA_SCREENSHOTS||folder;await mkdir(shots,{recursive:true});
const video=(name,filter)=>{
  const path=join(folder,name);
  execFileSync(process.env.FFMPEG_PATH||'ffmpeg',['-hide_banner','-loglevel','error','-y','-f','lavfi','-i',filter,'-c:v','libx264','-pix_fmt','yuv420p',path]);
  return path;
};
const red=video('短片.mp4','color=c=0x9b434d:s=640x360:r=12:d=2');
const pattern=video('长片.mp4','testsrc2=s=640x360:r=12:d=30');
const blue=video('待删除.mp4','color=c=0x365b8c:s=640x360:r=12:d=5');
const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.ico':'image/x-icon'};
const server=createServer(async(req,res)=>{
  const path=resolve(root,'public','.'+new URL(req.url,'http://local').pathname);
  if(!path.startsWith(join(root,'public')+'/')){res.writeHead(403).end();return;}
  try{res.setHeader('Content-Type',types[extname(path)]||'application/octet-stream');res.end(await readFile(path));}catch{res.writeHead(404).end();}
});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
let browser;
try{browser=await chromium.launch({headless:true});}catch{browser=await chromium.launch({channel:'chrome',headless:true});}
const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});
const errors=[];page.on('pageerror',e=>errors.push(e.stack));
const url='http://127.0.0.1:'+server.address().port+'/app.html';
const idle=()=>page.waitForFunction(()=>!__vfpQueue.active,null,{timeout:90000});
const checks=[];
const passed=name=>{checks.push(name);console.log('PASS',name);};
try {
  await page.goto(url);
  assert.equal(await page.locator('#storyFileInput,#seoTitle,#seoKeywords,#aiSeoModel').count(),0);
  assert.equal(await page.locator('#salesKitBtn').isDisabled(),true);
  await page.screenshot({path:join(shots,'01-empty-desktop.png'),fullPage:true});
  passed('image-only workflow with clear empty state');
  await page.locator('#vInput').setInputFiles([red,pattern,blue]);
  await page.waitForFunction(()=>__vfpProjects.list.length===3);
  await page.screenshot({path:join(shots,'02-video-queue.png'),fullPage:true});
  await page.locator('#salesKitBtn').click();
  await page.waitForFunction(()=>__vfpProjects.list[0].generationStatus==='complete'&&__vfpQueue.current?.id===2);
  await page.locator('#taskPauseBtn').click();
  await page.waitForFunction(()=>__vfpQueue.state==='paused');
  const progress=await page.evaluate(()=>__vfpProjects.list[1].generationProgress);
  await page.waitForTimeout(250);
  assert.equal(await page.evaluate(()=>__vfpProjects.list[1].generationProgress),progress);
  await page.locator('#taskResultsBtn').click();
  assert.equal(await page.locator('#view1').isVisible(),true);
  assert.equal(await page.locator('#batchList>.batch').count(),6);
  assert.equal(await page.locator('#batchList>.batch').first().isVisible(),true);
  assert.equal(await page.locator('#unifiedDownloadBtn').isEnabled(),true);
  await page.screenshot({path:join(shots,'03-results-while-paused.png'),fullPage:true});
  passed('first result is visible and exportable while remaining work is paused');
  const downloadPromise=page.waitForEvent('download');await page.locator('#unifiedDownloadBtn').click();
  const download=await downloadPromise,zip=await readFile(await download.path());
  const entries=await page.evaluate(bytes=>{
    const files=fflate.unzipSync(new Uint8Array(bytes));
    return {names:Object.keys(files),manifest:JSON.parse(fflate.strFromU8(files['图片清单.json']))};
  },[...zip]);
  assert.equal(entries.names.length,7);assert.ok(entries.names.every(x=>!x.includes('listing')));
  assert.ok(!('keywords' in entries.manifest)&&!('introduction' in entries.manifest));
  assert.equal(entries.manifest.assets.length,6);
  passed('ZIP contains actual images and source/output metadata only');
  await page.locator('#railBtn0').click();
  await page.getByRole('button',{name:'移除 待删除',exact:true}).click();
  assert.equal(await page.evaluate(()=>__vfpProjects.list.length),2);
  assert.equal(await page.evaluate(()=>__vfpQueue.state),'paused');
  await page.getByRole('button',{name:'移除 长片',exact:true}).click();
  await idle();
  assert.equal(await page.evaluate(()=>__vfpProjects.list.length),1);
  assert.equal(await page.evaluate(()=>__vfpProjects.list[0].batches.length),6);
  passed('delete queued and paused current videos without losing completed output');
  await page.locator('#vInput').setInputFiles(pattern);
  await page.locator('#salesKitBtn').click();
  await page.waitForFunction(()=>__vfpQueue.current?.id===4);
  await page.locator('#taskPauseBtn').click();
  await page.locator('#taskStopBtn').click();await idle();
  assert.equal(await page.evaluate(()=>__vfpProjects.list[1].generationStatus),'stopped');
  await page.locator('#salesKitBtn').click();
  await page.waitForFunction(()=>__vfpQueue.active);
  await page.locator('#taskResultsBtn').click();
  const viewed=await page.evaluate(()=>__vfpProjects.activeId);
  await idle();assert.equal(await page.evaluate(()=>__vfpProjects.activeId),viewed);
  assert.equal(await page.evaluate(()=>__vfpProjects.list[1].generationStatus),'complete');
  passed('stop, restart, and background completion preserve the currently viewed result');
  await page.evaluate(()=>switchResultProject(4));
  await page.locator('#final-2').click();
  assert.equal(await page.evaluate(()=>S.finalCoverId),2);
  await page.locator('.detail-edit-btn').first().click();
  assert.equal(await page.locator('#previewModal').isVisible(),true);
  await page.locator('#pmClose').click();
  const before=await page.evaluate(()=>S.batches[0].cells[0]);
  await page.evaluate(()=>{const b=S.batches[0];showFramePicker(b,0);});
  await page.locator('#framePicker .frame-picker-item').last().click();
  await page.waitForFunction(()=>S.batches.every(b=>b.canvas&&!b.rendering));
  assert.notEqual(await page.evaluate(()=>S.batches[0].cells[0]),before);
  const replaced=await page.evaluate(()=>S.batches[0].cells[0]);
  await page.evaluate(()=>undo());
  await page.waitForFunction(()=>S.batches.every(b=>b.canvas&&!b.rendering));
  assert.equal(await page.evaluate(()=>S.batches[0].cells[0]),before);
  await page.evaluate(()=>redo());
  await page.waitForFunction(()=>S.batches.every(b=>b.canvas&&!b.rendering));
  assert.equal(await page.evaluate(()=>S.batches[0].cells[0]),replaced);
  await page.evaluate(()=>{const b=S.batches[0];openCropEditor(b.id,0);_cropCtx.scale=1.4;saveCrop();});
  await page.waitForFunction(()=>S.batches.every(b=>b.canvas&&!b.rendering));
  assert.equal(await page.evaluate(()=>S.batches[0].crops[0].scale),1.4);
  await page.evaluate(()=>window.scrollTo(0,0));
  await page.screenshot({path:join(shots,'04-edited-results.png'),fullPage:true});
  passed('main-version selection, replacement, crop, undo and redo automatically redraw images');
  await page.evaluate(async()=>{document.getElementById('aiApiKey').value='test-key-never-persist';await saveWorkspaceNow();});
  const history=await page.evaluate(async()=>({id:WORKSPACE_SESSION_ID,payload:await readHistoryPayload(WORKSPACE_SESSION_ID)}));
  assert.ok(!JSON.stringify(history.payload).includes('test-key-never-persist'));
  assert.equal(history.payload.projects[1].finalCoverId,2);
  await page.reload();
  assert.equal(await page.evaluate(()=>__vfpProjects.list.length),0);
  await page.evaluate(id=>restoreHistoryRecord(id),history.id);
  await page.evaluate(()=>switchResultProject(4));
  await page.waitForFunction(()=>S.batches.every(b=>b.canvas));
  assert.equal(await page.evaluate(()=>S.finalCoverId),2);
  assert.equal(await page.evaluate(()=>S.batches[0].crops[0].scale),1.4);
  passed('history restores edited images, does not auto-open, and excludes credentials');
  await page.locator('#railBtn0').click();
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:join(shots,'05-mobile-queue.png'),fullPage:true});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
  await page.locator('#taskResultsBtn').click();
  await page.screenshot({path:join(shots,'06-mobile-results.png'),fullPage:true});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
  passed('mobile queue and results fit the viewport');
  // Fake the provider at the network boundary; no data or key leaves this test.
  let responseScores=[{idx:2,overall:9},{idx:1,overall:0,clarity:0}];
  await page.route('https://llm-api.mcisaas.com/v1/chat/completions',route=>route.fulfill({json:{choices:[{message:{content:JSON.stringify({scores:responseScores})}}]}}));
  const scored=await page.evaluate(()=>visionScoreBatch([{frameIdx:11,b64:'fake'},{frameIdx:22,b64:'fake'}],'fake-key','fake-model','',[],[],null,1000,null));
  assert.equal(scored[0].frameIdx,11);assert.equal(scored[0].overall,0);assert.equal(scored[0].clarity,0);assert.equal(scored[1].overall,.9);
  responseScores=[{idx:1,overall:9},{idx:1,overall:2}];
  const error=await page.evaluate(async()=>{try{await visionScoreBatch([{frameIdx:11,b64:'fake'},{frameIdx:22,b64:'fake'}],'fake','fake','',[],[],null,1000,null);return '';}catch(e){return e.message;}});
  assert.match(error,/重复/);
  passed('AI scores match candidate IDs, preserve zero, and reject ambiguous responses (mock provider)');
  await page.evaluate(()=>switchResultProject(PROJECTS.list[0].id));
  await page.waitForFunction(()=>S.batches.every(b=>b.canvas&&!b.rendering));
  await page.evaluate(()=>{
    startImageTasks([PROJECTS.list[0]]);
    __vfpQueue.pause();
  });
  assert.equal(await page.evaluate(()=>document.getElementById('batchList').inert),true);
  assert.equal(await page.locator('#unifiedDownloadBtn').isEnabled(),true);
  await page.evaluate(()=>__vfpQueue.stop());
  assert.equal(await page.evaluate(()=>document.getElementById('batchList').inert),false);
  assert.equal(await page.evaluate(()=>S.batches.length),6);
  passed('regeneration protects previous output from concurrent edits and preserves export after stop');
  await page.evaluate(async()=>{const ids=PROJECTS.list.map(p=>p.id);ids.forEach(deleteProjectNoConfirm);await saveWorkspaceNow();});
  assert.equal(await page.evaluate(id=>readHistoryPayload(id),history.id),null);
  passed('deleting the last video clears the current history row');
  await page.setViewportSize({width:1440,height:1000});
  await page.evaluate(()=>{
    DESKTOP_NATIVE.enabled=true;
    DESKTOP_NATIVE.invoke=async command=>command==='desktop_update_status'?{supported:true,version:'0.2.0'}:command==='check_desktop_update'?{version:'0.3.0',notes:'测试更新说明 <img src=x onerror=alert(1)>'}:null;
    initializeAppUpdater();
  });
  await page.waitForFunction(()=>desktopUpdater.state==='available');
  assert.equal(await page.locator('.desktop-update-banner').isVisible(),true);
  assert.equal(await page.locator('#desktopUpdateNotes img').count(),0);
  await page.locator('#desktopUpdateLater').click();
  assert.equal(await page.locator('.desktop-update-banner').isVisible(),false);
  await page.evaluate(()=>openSettingsDrawer());
  await page.locator('#desktopUpdateCheck').click();
  await page.waitForFunction(()=>desktopUpdater.state==='available');
  assert.equal(await page.locator('.desktop-update-banner').isVisible(),true);
  passed('Windows update notice can be deferred and checked again; release notes remain plain text');
  await page.evaluate(()=>{DESKTOP_NATIVE.enabled=false;});
  assert.deepEqual(errors,[]);
  await writeFile(join(shots,'browser-validation.json'),JSON.stringify({checks,errors},null,2));
  console.log('Screenshots:',shots);
} finally {await browser.close();await new Promise(r=>server.close(r));}
